import { MenuProvider } from '@/contexts/menuContext';

import { Alata } from 'next/font/google';
import './globals.css';

const alata = Alata({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={alata.className}>
        <MenuProvider>{children}</MenuProvider>
      </body>
    </html>
  );
}
